# docker-compose.yml
version: '3.8'

services:
  doc-ocr-backend: 
    build:
      context: ./doc-ocr-backend 
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - doc_ocr_backend_models:/root/.paddleocr/ 
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - ocr_network

  doc-ocr-frontend:  # Renamed service
    build:
      context: ./doc-ocr-frontend  # Updated context
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - doc-ocr-backend 
    environment:
      REACT_APP_API_URL: http://doc-ocr-backend:8000 
    networks:
      - ocr_network

volumes:
  doc_ocr_backend_models: 

networks:
  ocr_network:
    driver: bridge
