# docker-compose.yml
version: '3.8'

services:
  doc-ocr-backend: 
    container_name: doc-ocr-backend
    build:
      context: ./doc-ocr-backend 
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - doc_ocr_backend_models:/root/.paddleocr/ 
      - ./doc-ocr-backend/app:/app/app
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - ocr_network

  doc-ocr-frontend:  # Renamed service
    container_name: doc-ocr-frontend
    build:
      context: ./doc-ocr-frontend  # Updated context
      dockerfile: Dockerfile_Dev
    ports:
      - "${PORT}:5173"
    environment:
      BACKEND_HOST: doc-ocr-backend
      BACKEND_PORT: 8000 
    networks:
      - ocr_network
    volumes:
      - ./doc-ocr-frontend/src:/app/src
      - ./doc-ocr-frontend/public:/app/public
    depends_on:
      - doc-ocr-backend

volumes:
  doc_ocr_backend_models: 

networks:
  ocr_network:
    driver: bridge
