apiVersion: v1
kind: Service
metadata:
  name: doc-ocr-backend-service
  namespace: doc-ocr
spec:
  type: ClusterIP
  selector:
    app: doc-ocr-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000