apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-ocr-backend
  namespace: doc-ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-ocr-backend
  template:
    metadata:
      labels:
        app: doc-ocr-backend
    spec:
      containers:
      - name: doc-ocr-backend
        image: gcr.io/${PROJECT_ID}/doc-ocr-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: KAFKA_BROKER
          value: "local-kafka:29092"
        - name: MONGODB_URL
          value: "mongodb://mongodb:27017/ocr_demo"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: doc-ocr-backend
  namespace: doc-ocr
spec:
  selector:
    app: doc-ocr-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000