apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-ocr-frontend
  namespace: doc-ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-ocr-frontend
  template:
    metadata:
      labels:
        app: doc-ocr-frontend
    spec:
      containers:
      - name: doc-ocr-frontend
        image: gcr.io/${PROJECT_ID}/doc-ocr-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: doc-ocr-frontend
  namespace: doc-ocr
spec:
  selector:
    app: doc-ocr-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80