apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: doc-ocr-ingress
  namespace: doc-ocr
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "doc-ocr-ip"
    networking.gke.io/managed-certificates: "doc-ocr-certificate"
    kubernetes.io/ingress.class: "gce" 
    # For GKE Autopilot or newer GKE versions, you might not need kubernetes.io/ingress.class: "gce"
    # or you might use a different class like "gce-internal" if it were an internal LB.
    # For external, "gce" is usually correct or it's the default.
spec:
  rules:
  - host: doc-ocr.maoye.demo.altostrat.com
    http:
      paths:
      - path: /api/*
        pathType: Prefix 
        backend:
          service:
            name: doc-ocr-backend-service
            port:
              number: 8000
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: doc-ocr-frontend-service
            port:
              number: 80